#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt update
apt install -y haproxy=1.6.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3291-web-01 35.227.122.191:80 check
    server 3291-web-02 34.138.198.108:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start